# Generated by Django 5.1.2 on 2024-11-03 09:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='session_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
